# This are just examples

# Training settings
batch_size: 32
seed: 42
epochs: 30
metric: 'F1'
regularizer: 'l2'
regularization: 0

# Model
model: 'BERT' # RNN, etc.

preprocess:
    BERT: True
    RNN: True
    LSTM: False
    
# Some embedding config
embedder: 'GloVe' # Word2Vec, TfIdf, etc.

# Dataset
train_dir: 'data/train.csv'
test_dir: 'data/test.csv'

train_val_split: '0.3'

mlflow: True
save_model: True